Repository connect-foundation/2019-14, pull requests merged in 2019-11, with the labels that each got.

#69 에디터 헤더 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/components/EditorHeader.jsx
Labels: FE, High

#99 유저 기본 터미널 생성
  server/src/api/docker.js
  server/src/app.js
  server/src/routes/terminal.js
Labels: BE

#122 스타일 컴포넌트와 에디터 병합
  client/src/actions/CellAction.js
  client/src/actions/MarkdownAction.js
  client/src/components/editor/EditorComponent.jsx
  client/src/components/editor/EditorInput.jsx
  client/src/components/editor/MarkdownCell.jsx
  client/src/components/editor/style/MarkdownWrapper.jsx
  client/src/enums/CELL_TAG.js
  client/src/enums/MARKDOWN.js
  client/src/enums/THEME.js
  client/src/enums/index.js
  client/src/pages/EditorPage.jsx
  client/src/reducers/CellReducer.js
  client/src/reducers/MarkdownReducer.js
  client/src/stores/CellStore.jsx
Labels: FE
